// <auto-generated />
using System;
using ServicioDeDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Migraciones.Migrations
{
    [DbContext(typeof(ContextoDeElementos))]
    [Migration("20200306114825_AnadirTablaDeRoles")]
    partial class AnadirTablaDeRoles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gestor.Elementos.Permiso.PermisoReg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Clase")
                        .HasColumnName("CLASE")
                        .HasColumnType("INT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NOMBRE")
                        .HasColumnType("VARCHAR(250)");

                    b.Property<bool>("Permiso")
                        .HasColumnName("PERMISO")
                        .HasColumnType("BIT");

                    b.Property<bool>("Tiene")
                        .HasColumnName("TIENE")
                        .HasColumnType("BIT");

                    b.HasKey("Id");

                    b.ToTable("PERMISO","PERMISO");
                });

            modelBuilder.Entity("Gestor.Elementos.Permiso.RolPermisoReg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CursoId")
                        .HasColumnType("INT");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("RolRegId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("RolRegId");

                    b.ToTable("ROL_PERMISO","PERMISO");
                });

            modelBuilder.Entity("Gestor.Elementos.Permiso.RolReg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NOMBRE")
                        .HasColumnType("VARCHAR(250)");

                    b.HasKey("Id");

                    b.ToTable("ROL","PERMISO");
                });

            modelBuilder.Entity("Gestor.Elementos.Permiso.RolPermisoReg", b =>
                {
                    b.HasOne("Gestor.Elementos.Permiso.PermisoReg", "Curso")
                        .WithMany("Roles")
                        .HasForeignKey("CursoId");

                    b.HasOne("Gestor.Elementos.Permiso.RolReg", null)
                        .WithMany("Permisos")
                        .HasForeignKey("RolRegId");
                });
#pragma warning restore 612, 618
        }
    }
}
