
CREATE VIEW ENTORNO.USU_PERMISO
AS
select distinct t2.IDUSUA as IDUSUA, t4.IDPERMISO as IDPERMISO
from SEGURIDAD.USU_PUESTO t2 
inner join SEGURIDAD.ROL_PUESTO T3 ON T3.IDPUESTO = T2.IDPUESTO
INNER JOIN SEGURIDAD.ROL_PERMISO T4 ON T4.IDROL = T3.IDROL


--SELECT * 
--FROM ENTORNO.USUARIO T1
--INNER JOIN ENTORNO.USU_PERMISOS T2 ON T2.IDUSUA = T1.ID
--WHERE T2.IDPERMISO = 4